server:
    port: 8080

spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://localhost:3306/java?serverTimezone=UTC&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: "0000"
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true